
#include "C++ EXCEPTIONS THROW CATCH.h"

MyException::MyException(string message) {
		cout << "Error! " << message << endl;
}
